### ISSUE TITLE
Clarification du code

### ISSUE THREAD

**Issue by llextv** [ServerOpenMC/Wiki#8]
J'aimerais que l'on décide d'une norme commune pour le code du Wiki je m'explique:
Certaine page du Wiki sont faite grâce a du **Markdown** et certaine sont faite grâce a du <strong>HTML</strong>

**Comment by llextv** [comment]
(je préferais que l'on utilise du Markdown qui est plus lisible et facile a modifier)

**Comment by sajiterre** [comment]
Ben le markdown ses surtout fait pour sa

**Comment by llextv** [comment]
Ok je refferait tout en Markdown

**Comment by Margouta** [comment]
@llextv non. Gitbook prend en charge un mélange entre markdown et html. Il faut le respecter.
